### ISSUE TITLE
第一フェーズ: とりあえず書く

### ISSUE THREAD

**Issue by tyokinuhata** [AfterSchoolStudy/pug-study#3]
- 基礎編
  - [x] 概要
  - [x] 要素の書き方
  - [x] ネスト
  - [x] 改行
  - [x] 属性、値の書き方
  - [x] クラス、IDの書き方
  - [x] 改行とインデントの省略
  - [x] コメント
- 応用編
  - [x] 変数
  - [x] for, each
  - [x] include
  - [x] extends
- 実践編
  - [x] node, gulp, pugのインストール
  - [x] gulpでコンパイル

**Comment by tyokinuhata** [comment]
基礎編　たかし
応用編　実践編　かずきち

**Comment by takashi0602** [comment]
とりあえず、書き終わった
